Rithis\PublicationsBundle\Entity\EmptyBlock:
    type: entity
    table: publication_blocks
    repositoryClass: Gedmo\Sortable\Entity\Repository\SortableRepository
    inheritanceType: SINGLE_TABLE
    discriminatorColumn:
        name: block_type
        type: string
    discriminatorMap:
        empty: EmptyBlock
        text: TextBlock
    id:
        publication:
            associationKey: true
    fields:
        position:
            type: integer
            id: true
            length: 2
            gedmo:
                - sortablePosition
    manyToOne:
        publication:
            targetEntity: Publication
            inversedBy: blocks
            gedmo:
                - sortableGroup
            joinColumn:
                name: publication_id
                referencedColumnName: id
