Rithis\PublicationsBundle\Entity\Publication:
    type: entity
    table: publications
    fields:
        id:
            id: true
        resource: ~
        title: ~
    oneToMany:
        blocks:
            targetEntity: EmptyBlock
            mappedBy: publication
            cascade: [persist]
            orderBy:
                position: ASC
