Rithis\PublicationsBundle\Entity\Publication:
    type: entity
    table: publications
    fields:
        id:
            id: true
        resource:
            id: true
        title: ~
    oneToMany:
        blocks:
            targetEntity: EmptyBlock
            mappedBy: publication
            orderBy:
                position: ASC
