# Copyright 2012 Rithis Studio LLC
# Author Vyacheslav Slinko <vyacheslav.slinko@rithis.com>

imports:
    - { resource: parameters.dist.yml }
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    secret: %secret%
    router: { resource: "%kernel.root_dir%/config/routing.yml" }
    default_locale: ru
    templating: { engines: [twig] }
    form: ~
    csrf_protection: ~
    session: ~
    translator: ~

doctrine:
    dbal:
        driver: %database_driver%
        host: %database_host%
        port: %database_port%
        dbname: %database_name%
        user: %database_user%
        password: %database_password%
        path: %database_path%
        charset: UTF8
    orm:
        entity_managers:
            default:
                auto_mapping: true
                filters:
                    softdeleteable:
                        class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                        enabled: true

sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]

stof_doctrine_extensions:
    default_locale: ru_RU
    orm:
        default:
            timestampable: true
            sluggable: true
            softdeleteable: true

knp_paginator:
    template:
        pagination: RithisBootstrapBundle::pagination.html.twig

foq_elastica:
    clients:
        default: { host: localhost, port: 9200 }
    indexes:
        rithis:
            types:
                news:
                    mappings:
                        title:
                        description:
                        text:
                    persistence:
                        driver: orm
                        model: Rithis\NewsBundle\Entity\News
                        identifier: slug
                        provider:
                        listener:
