# Copyright 2012 Rithis Studio LLC
# Author Vyacheslav Slinko <vyacheslav.slinko@rithis.com>

imports:
    - { resource: config.yml }

framework:
    router: { resource: "%kernel.root_dir%/config/routing_dev.yml" }
    profiler: true

web_profiler:
    toolbar: true

monolog:
    handlers:
        main:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: debug
        firephp:
            type:  firephp
            level: info

rithis_website_index:
    rithis_news_news_get: RithisNewsBundle:News
