# Copyright 2012 Rithis Studio LLC
# Author Vyacheslav Slinko <vyacheslav.slinko@rithis.com>

_wdt:
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix: /_wdt

_profiler:
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix: /_profiler

_index:
    pattern: /
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: rithis_website_index_website_index_get }

_rithis_website_index:
    resource: "@RithisWebsiteIndexBundle/Resources/config/routing.yml"

_rithis_image_placeholder:
    resource: "@RithisImagePlaceholderBundle/Resources/config/routing.yml"
    prefix: _placeholder

_main:
    resource: routing.yml
